#!/usr/bin/env node

/**
 * Skill Creator - Create and optimize skills
 *
 * Usage:
 *   node creator.js create <skill-name> <description> [--with-script]
 *   node creator.js optimize <skill-path>
 *   node creator.js validate <skill-path>
 *   node creator.js list
 */

const fs = require('fs');
const path = require('path');
const RecordLogger = require('../logger/record-logger.js');
const RecordAnalyzer = require('../logger/record-analyzer.js');

const SKILL_TEMPLATE = `---
name: {name}
description: {description}
license: MIT
compatibility: opencode
metadata:
  audience: developers
  version: "1.0.0"
---

## What I do

- 功能点 1
- 功能点 2
- 功能点 3

## When to use me

- 使用场景 1
- 使用场景 2
- 使用场景 3

## 快速参考

<!-- 根据需要添加 -->

## 注意事项

- 注意事项 1
- 注意事项 2

## 参考文档

- [官方文档链接]
`;

const TOOL_SCRIPT_TEMPLATE = `#!/usr/bin/env node

/**
 * {skillName} - Tool Script
 * Generated by skill-creator
 */

const fs = require('fs');
const path = require('path');
const RecordLogger = require('../logger/record-logger.js');
const RecordAnalyzer = require('../logger/record-analyzer.js');

// CLI Handler
function handleCommand(command, args) {
  const logger = new RecordLogger('{skillName}');
  const analyzer = new RecordAnalyzer('{skillName}');

  logger.startCall(command, args);

  try {
    switch (command) {
      case 'check':
        console.log('Check command - TODO: implement');
        logger.logStep('Check executed', { command, args });
        break;
      case 'execute':
        console.log('Execute command - TODO: implement');
        logger.logStep('Execute completed', { command, args });
        break;
      default:
        console.log('Unknown command:', command);
        console.log('Available commands: check, execute');
        logger.logStep('Unknown command received', { command });
        logger.endCall(false, 'Unknown command');
        return;
    }

    logger.endCall(true);

    // Trigger analysis asynchronously
    setTimeout(() => {
      analyzer.analyze();
    }, 0);

  } catch (error) {
    logger.endCall(false, error.message);
    console.error('Error:', error.message);
    process.exit(1);
  }
}

// CLI Entry Point
const command = process.argv[2];
const args = process.argv.slice(3);

if (!command) {
  console.log(\`{skillName} - Tool Script\\n\`);
  console.log('Usage:');
  console.log(\`  node {scriptName}.js <command> [args]\\n\`);
  console.log('Commands:');
  console.log('  check     - Check status');
  console.log('  execute   - Execute task');
  process.exit(0);
}

handleCommand(command, args);
`;

const RECORDS_GITIGNORE_TEMPLATE = `# Skill records
*.json
!.gitignore
`;

const FRONTMATTER_REGEX = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/;
const NAME_REGEX = /name:\s*([a-z0-9]+(-[a-z0-9]+)*)/;
const DESCRIPTION_REGEX = /description:\s*(.+)/;

function validateSkillName(name) {
  const regex = /^[a-z0-9]+(-[a-z0-9]+)*$/;
  if (!regex.test(name)) {
    return {
      valid: false,
      error: `Invalid name "${name}". Must match: ^[a-z0-9]+(-[a-z0-9]+)*$`
    };
  }
  return { valid: true };
}

function validateFrontmatter(content) {
  const match = content.match(FRONTMATTER_REGEX);
  if (!match) {
    return { valid: false, error: 'Missing frontmatter' };
  }

  const frontmatter = match[1];
  const body = match[2];

  const nameMatch = frontmatter.match(NAME_REGEX);
  if (!nameMatch) {
    return { valid: false, error: 'Missing or invalid name field' };
  }

  const descMatch = frontmatter.match(DESCRIPTION_REGEX);
  if (!descMatch) {
    return { valid: false, error: 'Missing description field' };
  }

  const description = descMatch[1];
  if (description.length < 1 || description.length > 1024) {
    return { valid: false, error: 'Description must be 1-1024 characters' };
  }

  return {
    valid: true,
    name: nameMatch[1],
    description: description,
    bodyLength: body.length
  };
}

function createSkill(skillName, description, options = {}) {
  const logger = new RecordLogger('skill-creator');
  const analyzer = new RecordAnalyzer('skill-creator');

  logger.startCall('create', { skillName, description, options });

  try {
    const result = validateSkillName(skillName);
    if (!result.valid) {
      logger.endCall(false, result.error);
      console.error('Error:', result.error);
      process.exit(1);
    }

    const skillDir = path.join(__dirname, '..', skillName);
    const skillFile = path.join(skillDir, 'SKILL.md');
    const recordsDir = path.join(skillDir, 'records');
    const gitignoreFile = path.join(recordsDir, '.gitignore');

    if (fs.existsSync(skillDir)) {
      const error = `Skill "${skillName}" already exists`;
      logger.endCall(false, error);
      console.error(`Error: ${error}`);
      process.exit(1);
    }

    fs.mkdirSync(skillDir, { recursive: true });
    fs.mkdirSync(recordsDir, { recursive: true });

    const content = SKILL_TEMPLATE
      .replace('{name}', skillName)
      .replace('{description}', description);

    fs.writeFileSync(skillFile, content, 'utf8');
    fs.writeFileSync(gitignoreFile, RECORDS_GITIGNORE_TEMPLATE, 'utf8');

    const files = [skillFile, gitignoreFile];

    // Create tool script if requested
    if (options.withScript) {
      const scriptFile = path.join(skillDir, `${skillName}.js`);
      const scriptContent = TOOL_SCRIPT_TEMPLATE.replace(/\{skillName\}/g, skillName);
      fs.writeFileSync(scriptFile, scriptContent, 'utf8');
      files.push(scriptFile);
      logger.logStep('Tool script created', { scriptFile });
    }

    logger.logStep('Skill created', { skillName, files });

    console.log(`Created skill: ${skillName}`);
    console.log(`  - ${skillFile}`);
    console.log(`  - ${recordsDir}/.gitignore`);
    if (options.withScript) {
      console.log(`  - ${skillDir}/${skillName}.js`);
    }

    logger.endCall(true);

    // Trigger analysis asynchronously
    setTimeout(() => {
      analyzer.analyze();
    }, 0);

  } catch (error) {
    logger.endCall(false, error.message);
    console.error('Error:', error.message);
    throw error;
  }
}

function optimizeSkill(skillPath) {
  const logger = new RecordLogger('skill-creator');
  const analyzer = new RecordAnalyzer('skill-creator');

  logger.startCall('optimize', { skillPath });

  try {
    let fullPath = skillPath;
    if (!skillPath.includes('SKILL.md')) {
      fullPath = path.join(skillPath, 'SKILL.md');
    }

    if (!fs.existsSync(fullPath)) {
      const error = `SKILL.md not found at ${fullPath}`;
      logger.endCall(false, error);
      console.error(`Error: ${error}`);
      process.exit(1);
    }

    const content = fs.readFileSync(fullPath, 'utf8');
    const validation = validateFrontmatter(content);

    if (!validation.valid) {
      logger.endCall(false, validation.error);
      console.error('Validation Error:', validation.error);
      process.exit(1);
    }

    const lines = content.split('\n');
    const lineCount = lines.length;

    console.log(`Optimizing: ${validation.name}`);
    console.log(`  Current lines: ${lineCount}`);
    console.log(`  Description: ${validation.description}`);

    const hasWhatIDo = content.includes('## What I do');
    const hasWhenToUseMe = content.includes('## When to use me');

    if (hasWhatIDo && hasWhenToUseMe) {
      console.log('  Status: Already optimized (has What I do / When to use me)');
      logger.logStep('Already optimized', { skillName: validation.name, lineCount });
    } else {
      console.log('  Status: Needs optimization');
      console.log('  Hint: Add "## What I do" and "## When to use me" sections');
      logger.logStep('Needs optimization', { skillName: validation.name, lineCount });
    }

    if (lineCount > 100) {
      const estimatedReduction = Math.round((lineCount - 100) / lineCount * 100);
      console.log(`  Suggestion: Can reduce by ~${estimatedReduction}% (target: <100 lines)`);
    } else {
      console.log(`  Status: Within target range (<100 lines)`);
    }

    logger.endCall(true);

    setTimeout(() => {
      analyzer.analyze();
    }, 0);

  } catch (error) {
    logger.endCall(false, error.message);
    console.error('Error:', error.message);
    throw error;
  }
}

function validateSkill(skillPath) {
  const logger = new RecordLogger('skill-creator');
  const analyzer = new RecordAnalyzer('skill-creator');

  logger.startCall('validate', { skillPath });

  try {
    let fullPath = skillPath;
    if (!skillPath.includes('SKILL.md')) {
      fullPath = path.join(skillPath, 'SKILL.md');
    }

    if (!fs.existsSync(fullPath)) {
      const error = `SKILL.md not found at ${fullPath}`;
      logger.endCall(false, error);
      console.error(`Error: ${error}`);
      process.exit(1);
    }

    const content = fs.readFileSync(fullPath, 'utf8');
    const validation = validateFrontmatter(content);

    console.log(`Validating: ${fullPath}`);
    console.log('');

    if (validation.valid) {
      console.log('✅ Frontmatter valid');
      console.log(`  Name: ${validation.name}`);
      console.log(`  Description: ${validation.description}`);
      console.log(`  Body length: ${validation.bodyLength} chars`);
      logger.logStep('Validation passed', { skillName: validation.name });
    } else {
      console.log('❌ Frontmatter invalid');
      console.log(`  Error: ${validation.error}`);
      logger.endCall(false, validation.error);
      process.exit(1);
    }

    const hasWhatIDo = content.includes('## What I do');
    const hasWhenToUseMe = content.includes('## When to use me');

    console.log('');
    if (hasWhatIDo && hasWhenToUseMe) {
      console.log('✅ Structure: Optimized format');
    } else {
      console.log('⚠️  Structure: Not optimized (missing What I do / When to use me)');
    }

    const lines = content.split('\n').length;
    console.log('');
    if (lines > 150) {
      console.log(`⚠️  Length: ${lines} lines (consider reducing)`);
    } else if (lines > 100) {
      console.log(`⚠️  Length: ${lines} lines (target: <100)`);
    } else {
      console.log(`✅ Length: ${lines} lines`);
    }

    logger.endCall(true);

    setTimeout(() => {
      analyzer.analyze();
    }, 0);

  } catch (error) {
    logger.endCall(false, error.message);
    console.error('Error:', error.message);
    throw error;
  }
}

function listSkills() {
  const logger = new RecordLogger('skill-creator');

  logger.startCall('list', {});

  try {
    const skillsDir = path.join(__dirname, '..');
    const dirs = fs.readdirSync(skillsDir)
      .filter(f => {
        const stat = fs.statSync(path.join(skillsDir, f));
        return stat.isDirectory() && !f.startsWith('.');
      })
      .filter(f => {
        return fs.existsSync(path.join(skillsDir, f, 'SKILL.md'));
      });

    console.log('Available skills:');
    dirs.forEach(dir => {
      const skillFile = path.join(skillsDir, dir, 'SKILL.md');
      const content = fs.readFileSync(skillFile, 'utf8');
      const match = content.match(DESCRIPTION_REGEX);
      const desc = match ? match[1].substring(0, 60) + '...' : 'No description';
      console.log(`  ${dir}`);
      console.log(`    ${desc}`);
    });

    logger.logStep('Listed skills', { count: dirs.length });
    logger.endCall(true);

  } catch (error) {
    logger.endCall(false, error.message);
    console.error('Error:', error.message);
    throw error;
  }
}

// Main CLI
const action = process.argv[2];

switch (action) {
  case 'create': {
    const skillName = process.argv[3];
    const description = process.argv[4] || 'Skill description';
    const withScript = process.argv.includes('--with-script');
    if (!skillName) {
      console.error('Usage: creator.js create <skill-name> [description] [--with-script]');
      process.exit(1);
    }
    createSkill(skillName, description, { withScript });
    break;
  }

  case 'optimize': {
    const optimizePath = process.argv[3] || '.';
    optimizeSkill(optimizePath);
    break;
  }

  case 'validate': {
    const validatePath = process.argv[3] || '.';
    validateSkill(validatePath);
    break;
  }

  case 'list':
    listSkills();
    break;

  case 'help':
  default:
    console.log('Skill Creator - Create and optimize skills');
    console.log('');
    console.log('Usage:');
    console.log('  creator.js create <name> [description] [--with-script]  Create new skill');
    console.log('  creator.js optimize [path]                         Optimize existing skill');
    console.log('  creator.js validate [path]                         Validate skill format');
    console.log('  creator.js list                                  List all skills');
    console.log('');
    console.log('Examples:');
    console.log('  creator.js create my-skill "My skill description"');
    console.log('  creator.js create my-skill "Description" --with-script');
    console.log('  creator.js optimize ../other-skill');
    console.log('  creator.js validate ./my-skill');
}

module.exports = { validateFrontmatter, validateSkillName };
